name: Release

on:
    push:
        branches: [ main ]

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 18 ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node }}
                    cache: 'npm'

            -   name: Install dependencies
                run: npm ci --legacy-peer-deps

            -   name: Install semantic-release plugins
                run: npm install --save-dev @semantic-release/changelog @semantic-release/git --legacy-peer-deps

            #      - name: Test
            #        run: npm run test

            -   name: Build
                run: npm run build:prod

            -   name: Release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
                run: npx semantic-release
